version: "3.8"

services:

  node:
    volumes:
      - ./app:/app
      - node_modules:/app/node_modules
      - node:/app/.node
    command: sh -c "npx prisma db push npm run start"

volumes:
  node_modules:
  node: